version: '3.7'
   
services:
  web:
    build: .
    command: gunicorn budband.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/code
      - static_volume:/usr/src/code/staticfiles
      - media_volume:/usr/src/code/mediafiles
    expose:
      - 8000
    env_file:
      ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      ./.env.dev.db

  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/usr/src/code/staticfiles
      - media_volume:/usr/src/code/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

  # frontend:
  #   build: .
  #   command: xe

volumes:
  data:
  static_volume:
  media_volume:
