version: '3.7'
   
services:
  web:
    build: .
    command: gunicorn budband.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/code/staticfiles
      - media_volume:/usr/src/code/mediafiles
    expose:
      - 8000
    env_file:
      ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data

  # nginx-proxy:
  #   container_name: nginx-proxy
  #   build: nginx
  #   restart: always
  #   ports: 
  #     - 443:443
  #     - 80:80
  #   volumes:
  #     - static_volume:/usr/src/code/staticfiles
  #     - media_volume:/usr/src/code/mediafiles
  #     - certs:/etc/nginx/certs
  #     - html:/usr/share/nginx/html
  #     - vhost:/etc/nginx/vhost.d
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   depends_on:
  #     - web

  # nginx-proxy-letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   env_file:
  #     - .env.dev.proxy-companion
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - certs:/etc/nginx/certs
  #     - html:/usr/share/nginx/html
  #     - vhost:/etc/nginx/vhost.d
  #   depends_on:
  #     - nginx-proxy

  nginx:
    build: nginx
    volumes:
      - static_volume:/usr/src/code/staticfiles
      - media_volume:/usr/src/code/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  data:
  static_volume:
  media_volume:
  # certs:
  # html:
  # vhost: