# Generated by Django 3.1.6 on 2021-02-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud_band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifysong',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
