# Generated by Django 3.1.6 on 2021-02-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bud_band', '0004_auto_20210211_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotifysongcomment',
            options={'ordering': ['created_at']},
        ),
    ]
