# Generated by Django 3.1.7 on 2021-02-22 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bud_band', '0005_auto_20210211_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
