# Generated by Django 3.1.7 on 2021-03-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bud_band', '0007_auto_20210308_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='name',
        ),
    ]
