# Generated by Django 3.1.7 on 2021-03-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bud_band', '0009_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='artwork',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
